FROM python:3.9

COPY ./requirements.txt /requirements.txt

RUN pip install --no-cache-dir --upgrade -r /requirements.txt

COPY message-router.py /message-router.py

CMD ["python", "message-router.py", "--host", "0.0.0.0", "--port", "8888"]